/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bracuclassroom;

import static bracuclassroom.HomePageFacultyOntheGo.FacultyID;
import javax.swing.JFrame;
import java.text.*;
import java.sql.*;
import java.util.logging.Logger;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class HomePageFacultyOntheGo2 extends javax.swing.JFrame {
public static String FacultyID;
    /**
     * Creates new form HomePageFacultyOntheGo2
     */
    public HomePageFacultyOntheGo2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jPanelJtableDisplay = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Faculty_Course_Section = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTextField_Section = new javax.swing.JTextField();
        jTextField_EnterID = new javax.swing.JTextField();
        jComboBoxTest = new javax.swing.JComboBox<>();
        jButton_Submit = new javax.swing.JButton();
        jTextField_Marks = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_Course = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(127, 143, 166));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelJtableDisplay.setBackground(new java.awt.Color(64, 115, 158));
        jPanelJtableDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelJtableDisplayMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Course Taken");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bracuclassroom/images/open-book (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanelJtableDisplayLayout = new javax.swing.GroupLayout(jPanelJtableDisplay);
        jPanelJtableDisplay.setLayout(jPanelJtableDisplayLayout);
        jPanelJtableDisplayLayout.setHorizontalGroup(
            jPanelJtableDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJtableDisplayLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJtableDisplayLayout.setVerticalGroup(
            jPanelJtableDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJtableDisplayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidepane.add(jPanelJtableDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, -1));

        jPanel4.setBackground(new java.awt.Color(64, 115, 158));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Go back");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bracuclassroom/images/door.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );

        sidepane.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 180, 50));

        jPanel5.setBackground(new java.awt.Color(64, 115, 158));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5JPanel5Table2(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Post Grades");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bracuclassroom/images/grades.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );

        sidepane.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 160, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home Page");
        sidepane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jPanel8.setBackground(new java.awt.Color(64, 115, 158));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Show Statistics");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bracuclassroom/images/pie-chart.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidepane.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 180, 50));

        jPanel9.setBackground(new java.awt.Color(64, 115, 158));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("weak students");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel16)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        sidepane.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 70));

        getContentPane().add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 440));

        jPanel1.setBackground(new java.awt.Color(131, 149, 167));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 790, 100));

        jTable_Faculty_Course_Section.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_Faculty_Course_Section.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Section", "Student Name", "Student ID", "Quiz 1", "Quiz 2", "Quiz 3", "Assignment", "Mid Exam", "Final Exam", "Marks before mids", "Marks Before Final", "Final Grade", "Course"
            }
        ));
        jTable_Faculty_Course_Section.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable_Faculty_Course_Section);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 790, 200));

        jPanel3.setBackground(new java.awt.Color(127, 143, 166));

        jTextField_Section.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SectionActionPerformed(evt);
            }
        });

        jTextField_EnterID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jComboBoxTest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxTest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quiz1", "Quiz2", "Quiz3", "Assignment", "MidExam", "FinalExam" }));
        jComboBoxTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTestActionPerformed(evt);
            }
        });

        jButton_Submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Submit.setText("Submit Marks");
        jButton_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SubmitActionPerformed(evt);
            }
        });

        jTextField_Marks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setText("SECTION");

        jLabel3.setText("StudentID");

        jLabel13.setText("Marks");

        jLabel10.setText("Course");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(83, 83, 83)
                .addComponent(jLabel10)
                .addGap(90, 90, 90)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(220, 220, 220))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTextField_Section, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jTextField_Course, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jTextField_EnterID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxTest, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Marks, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton_Submit)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Section, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_EnterID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Submit)
                    .addComponent(jTextField_Marks, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Course, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 790, 140));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/////////////////////////////////////////////////////////WHAT I WANTED
    private void jPanelJtableDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelJtableDisplayMouseClicked
HomePageFacultyOntheGo rgf = new HomePageFacultyOntheGo();
rgf.FacultyID=FacultyID;
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        this.dispose();
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        try {
            rgf.show_table();
        } catch (Exception ex) {
            Logger.getLogger(HomePageFacultyOntheGo.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_jPanelJtableDisplayMouseClicked
/////////////////////////////////////////////////////////WHAT I WANTED
    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
      
          HomePageFacultyOntheGo SS=new HomePageFacultyOntheGo();
        SS.FacultyID=FacultyID;
        SS.setVisible(true);
        SS.pack();
        SS.setLocationRelativeTo(null);
        this.dispose();   ///setting my sail to the homepage
        SS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();   ///setting my sail to the homepage
        //      J.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel5JPanel5Table2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5JPanel5Table2

        
        ///////////////////////////////////////////////////
        HomePageFacultyOntheGo2 obj = new HomePageFacultyOntheGo2();
        obj.FacultyID=FacultyID;
        obj.setVisible(true);
        obj.pack();
        obj.setLocationRelativeTo(null);
        this.dispose();   ///setting my sail to the homepage
        obj.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
          try {
         obj.show_table();
     } catch (Exception ex) {
         Logger.getLogger(HomePageFacultyOntheGo2.class.getName()).log(Level.SEVERE, null, ex);
     }
        //////////////////////////////////////////////////////
        
        

        /////this is lowkey refreshing
        //then what to do we do

        
        
    }//GEN-LAST:event_jPanel5JPanel5Table2

    private void jTextField_SectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SectionActionPerformed

    private void jComboBoxTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTestActionPerformed

        
    }//GEN-LAST:event_jComboBoxTestActionPerformed

    private void jButton_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SubmitActionPerformed
////trouble
        String Section=jTextField_Section.getText();
        String StudentID=jTextField_EnterID.getText();
     String Course=jTextField_Course.getText();
String Marks = jTextField_Marks.getText();  //shobai string
   // String Selecteditem=jComboBoxTest.getSelectedItem().toString();
//       jTextField_TEST.setText(Selecteditem);
       String TestType=jComboBoxTest.getSelectedItem().toString();
       try {    ///bad programming practice indeed
       ///have to use if and else kichui korar nai
       PreparedStatement ps1 = null; //the particular student in hand
       if("Quiz1".equals(TestType)){
       String query="UPDATE `facultystudent` set `Quiz1` = ?  where `Section` = ? AND `StudentID` =? AND `Course`=? " ;    ////trouble
                   ps1 = MyConnection.getConnection().prepareStatement(query);
       }else if("Quiz2".equals(TestType)){
       String query="UPDATE `facultystudent` set `Quiz2` = ?  where `Section` = ? AND `StudentID` =? AND `Course`=? ";    ////trouble
                   ps1 = MyConnection.getConnection().prepareStatement(query);
       }else if("Quiz3".equals(TestType)){
       String query="UPDATE `facultystudent` set `Quiz3` = ?  where `Section` = ? AND `StudentID` =? AND `Course`=? ";    ////trouble
                   ps1 = MyConnection.getConnection().prepareStatement(query);
       }else if("Assignment".equals(TestType)){
       String query="UPDATE `facultystudent` set `Assignment` = ?  where `Section` = ? AND `StudentID` =? AND `Course`=?";    ////trouble
                   ps1 = MyConnection.getConnection().prepareStatement(query);
       }else if("MidExam".equals(TestType)){
       String query="UPDATE `facultystudent` set `MidExam` = ?  where `Section` = ? AND `StudentID` =? AND `Course`=?";    ////trouble
                   ps1 = MyConnection.getConnection().prepareStatement(query);
       }else if("FinalExam".equals(TestType)){
       String query="UPDATE `facultystudent` set `FinalExam` = ?  where `Section` = ? AND `StudentID` =? AND `Course`=?";    ////trouble
                   ps1 = MyConnection.getConnection().prepareStatement(query);
       }else{
       String query="UPDATE `facultystudent` set `FinalGrade` = ?  where `Section` = ? AND `StudentID` =? AND `Course`=?";    ////trouble
                   ps1 = MyConnection.getConnection().prepareStatement(query);
       }


        
        // ps1.setString(1,TestType);
         ps1.setString(1,Marks);
         ps1.setString(2,Section);
         ps1.setString(3,StudentID);
         ps1.setString(4,Course);
          ps1.executeUpdate();
          System.out.println("Current Student in consideration "+StudentID);
          ////////////////////////////////////////////Calculation of grades
           /////////////////////////////////////////////////Calculation of grades
 /////////////////////////////////////////////////Calculation of grades
/////////////////////////////////////////////////Calculation of grades
          
            PreparedStatement ps;
//ArrayList<Faculty> facultyList=new ArrayList<>();
//this is the array
System.out.println("CALCULATIO BEGIN");

    try{ 
 String query1="SELECT * FROM mydb.facultystudent WHERE `FacultyID`=? AND `StudentID`=? "; //////the query that filters
   ps = MyConnection.getConnection().prepareStatement(query1);
    ps.setString(1, FacultyID);
    ps.setString(2, StudentID);     
// Statement st=conn.createStatement();
 ResultSet rs1; //=st.executeQuery(query1);
 rs1 = ps.executeQuery();
// int Quiz1;
// int Quiz2;
// int Quiz3;
// int Assignment;
// int Mid;
// int Final;
 CalculationOfGrades grade = null;
 
 while(rs1.next()){
 grade=new CalculationOfGrades(rs1.getInt("Quiz1"),rs1.getInt("Quiz2"),rs1.getInt("Quiz3"),rs1.getInt("Assignment"),rs1.getInt("MidExam"),rs1.getInt("FinalExam"),rs1.getInt("TotalMarksBeforeMid"),rs1.getInt("TotalMarksFinal"),rs1.getString("FinalGrade")); //ektar na basically shobar tai ase not just a single row not a single tuple
 
///GETTING THE RAW DATA FROM THE DATABASE AND SAVING IT IN VARIABLES in faculty.java
 //faculty list is an array over here
 //time for the calculation of the grades in another class
 
 }
 //TIME TO FILL IN THE DATA
 
  int BeforeMids=grade.getTotalMarksBeforeMid();
  int Finals=grade.getTotalMarksFinal();
  PreparedStatement ps2 = null;
  PreparedStatement ps3 = null;
  PreparedStatement ps4 = null;
//  System.out.println("BEFORE MIDS"+grade.getTotalMarksBeforeMid());
//  System.out.println("FINALS"+grade.getTotalMarksFinal());

       String query2="UPDATE `facultystudent` set `TotalMarksBeforeMid` = ?   WHERE `Section` = ? AND `StudentID` =?"; 
       String query3="UPDATE `facultystudent` set `TotalMarksFinal` = ?   WHERE `Section` = ? AND `StudentID` =?";
       String query4="UPDATE `facultystudent` set `FinalGrade` = ?   WHERE `Section` = ? AND `StudentID` =?";
 
       ps2 = MyConnection.getConnection().prepareStatement(query2);
       ps2.setString(1,String.valueOf(BeforeMids)); // String.valueOf(int)
       ps2.setString(2,Section);
       ps2.setString(3,StudentID);
       ps2.executeUpdate();
       
       ps3 = MyConnection.getConnection().prepareStatement(query3);
       ps3.setString(1,String.valueOf(Finals));
       ps3.setString(2,Section);
       ps3.setString(3,StudentID);
       ps3.executeUpdate();
       
       
        ps4 = MyConnection.getConnection().prepareStatement(query4);
       ps4.setString(1,grade.getFinalGrade()); // String.valueOf(int)
       ps4.setString(2,Section);
       ps4.setString(3,StudentID);
       ps4.executeUpdate();
       
       
}catch(Exception ex){
    Logger.getLogger(MyConnection.class.getName()).log(Level.SEVERE,null,ex);
 }
          /////////////////////////////////////////////////Calculation of grades
          /////////////////////////////////////////////////Calculation of grades
          /////////////////////////////////////////////////Calculation of grades
          /////////////////////////////////////////////////Calculation of grades
          //here goes nth
          ////then we refresh
            ///////////////////////////////////////////////////
        HomePageFacultyOntheGo2 obj = new HomePageFacultyOntheGo2();
        obj.FacultyID=FacultyID;
        obj.setVisible(true);
        obj.pack();
        obj.setLocationRelativeTo(null);
        this.dispose();   ///setting my sail to the homepage
        obj.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           try {
         obj.show_table();
     } catch (Exception ex) {
         Logger.getLogger(HomePageFacultyOntheGo2.class.getName()).log(Level.SEVERE, null, ex);
     }
        //////////////////////////////////////////////////////
        
    } catch (SQLException ex) {
        Logger.getLogger(HomePageFacultyOntheGo2.class.getName()).log(Level.SEVERE, null, ex);
    }
     

        
        
        
    }//GEN-LAST:event_jButton_SubmitActionPerformed

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked

              SectionSelection SS=new SectionSelection();
 SS.FacultyID=FacultyID;
        SS.setVisible(true);
        SS.pack();
        SS.setLocationRelativeTo(null);
        this.dispose();   ///setting my sail to the homepage
        SS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();   ///setting my sail to the homepage
  //      J.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        
        
        
        
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked

        MarkedStudent SS=new MarkedStudent();
        SS.FacultyID=FacultyID;
        SS.setVisible(true);
        SS.pack();
        SS.setLocationRelativeTo(null);
        this.dispose();   ///setting my sail to the homepage
        SS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();   ///setting my sail to the homepage
        //      J.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }//GEN-LAST:event_jPanel9MouseClicked

 public ArrayList<Faculty> facultylist() throws Exception{
    PreparedStatement ps;
ArrayList<Faculty> facultyList=new ArrayList<>();
    try{
//        Connection conn = null;
//Class.forName("com.mysql.cj.jdbc.Driver");  
//        //Connection DriverManager = null;
// conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","root");
 /////////////////////////////////////////////////////////////////////////////////////////////////////////For Marks

 
 
 String query1="SELECT * FROM mydb.facultystudent WHERE `FacultyID`=? "; //////the query that filters
   ps = MyConnection.getConnection().prepareStatement(query1);
    ps.setString(1, FacultyID);
         
// Statement st=conn.createStatement();
 ResultSet rs; //=st.executeQuery(query1);
 rs = ps.executeQuery();
 Faculty faculty;
 while(rs.next()){
 faculty=new Faculty(rs.getString("FacultyName"),rs.getString("FacultyID"),rs.getString("StudentName"),rs.getString("StudentID"),rs.getString("Section"),rs.getString("CurrentSemester"),rs.getString("Course"),rs.getInt("Quiz1"),rs.getInt("Quiz2"),rs.getInt("Quiz3"),rs.getInt("Assignment"),rs.getInt("MidExam"),rs.getInt("FinalExam"),rs.getInt("TotalMarksBeforeMid"),rs.getInt("TotalMarksFinal"),rs.getString("FinalGrade"));
 facultyList.add(faculty); ///GETTING THE RAW DATA FROM THE DATABASE AND SAVING IT IN VARIABLES in faculty.java
 //faculty list is an array over here
 
 }
 
 
 
 
//System.out.println("Successss");
}catch(Exception ex){
    Logger.getLogger(MyConnection.class.getName()).log(Level.SEVERE,null,ex);
 }


return facultyList;

//now display
        }
   public void show_table() throws Exception{
    ArrayList<Faculty> list= facultylist();
    DefaultTableModel model =(DefaultTableModel)jTable_Faculty_Course_Section.getModel();
    Object[] row =new Object[13];
    for(int i=0;i<list.size();i++){
    row[0]=list.get(i).getSection();
    row[1]=list.get(i).getStudentName();
    row[2]=list.get(i).getStudentID();
    row[3]=list.get(i).getQuiz1();
    row[4]=list.get(i).getQuiz2();
    row[5]=list.get(i).getQuiz3();
    row[6]=list.get(i).getAssignment();
    row[7]=list.get(i).getMidExam();
    row[8]=list.get(i).getFinalExam();
    row[9]=list.get(i).getTotalMarksBeforeMid();
    row[10]=list.get(i).getTotalMarksFinal();
    row[11]=list.get(i).getFinalGrade();
    row[12]=list.get(i).getCourse();
    model.addRow(row);     
    }
    
    
    }
    
              
    
    private void JPanel5Table2(java.awt.event.MouseEvent evt) {                               

        
         HomePageFacultyOntheGo2 obj = new HomePageFacultyOntheGo2();
         obj.FacultyID=FacultyID;
    obj.setVisible(true);
    obj.pack();
    obj.setLocationRelativeTo(null);
    this.dispose();   ///setting my sail to the homepage
    obj.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    
    
   
    /////this is lowkey refreshing
    //then what to do we do
      
    } 

      public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageFacultyOntheGo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageFacultyOntheGo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageFacultyOntheGo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageFacultyOntheGo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageFacultyOntheGo().setVisible(true);
            }
        });
    }
      
      

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Submit;
    private javax.swing.JComboBox<String> jComboBoxTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelJtableDisplay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Faculty_Course_Section;
    private javax.swing.JTextField jTextField_Course;
    private javax.swing.JTextField jTextField_EnterID;
    private javax.swing.JTextField jTextField_Marks;
    private javax.swing.JTextField jTextField_Section;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables


}