 package bracuclassroom;
import javax.swing.JFrame;
import java.text.*;
import java.sql.*;
import java.util.logging.Logger;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author hamza
 */
public class RegisterStudent extends javax.swing.JFrame {

    /**
     * Creates new form RegisterStudent
     */
    public RegisterStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JTextField_userid = new javax.swing.JTextField();
        JTextField_semester = new javax.swing.JTextField();
        JTextField_course = new javax.swing.JTextField();
        JPasswordField_password = new javax.swing.JPasswordField();
        JPasswordField_confirmpassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        registerbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(64, 107, 125));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Register for this semester");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTextField_userid.setBackground(new java.awt.Color(64, 107, 125));
        JTextField_userid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTextField_userid.setForeground(new java.awt.Color(255, 255, 255));
        JTextField_userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_useridActionPerformed(evt);
            }
        });

        JTextField_semester.setBackground(new java.awt.Color(64, 107, 125));
        JTextField_semester.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTextField_semester.setForeground(new java.awt.Color(255, 255, 255));
        JTextField_semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_semesterActionPerformed(evt);
            }
        });

        JTextField_course.setBackground(new java.awt.Color(64, 107, 125));
        JTextField_course.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTextField_course.setForeground(new java.awt.Color(255, 255, 255));
        JTextField_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_courseActionPerformed(evt);
            }
        });

        JPasswordField_password.setBackground(new java.awt.Color(64, 107, 125));
        JPasswordField_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JPasswordField_password.setForeground(new java.awt.Color(255, 255, 255));
        JPasswordField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPasswordField_passwordActionPerformed(evt);
            }
        });

        JPasswordField_confirmpassword.setBackground(new java.awt.Color(64, 107, 125));
        JPasswordField_confirmpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JPasswordField_confirmpassword.setForeground(new java.awt.Color(255, 255, 255));
        JPasswordField_confirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPasswordField_confirmpasswordActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(90, 150, 191));
        jLabel7.setText("User ID:");

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(90, 150, 191));
        jLabel9.setText("Semester:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(90, 150, 191));
        jLabel5.setText("Course:");

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(90, 150, 191));
        jLabel8.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(90, 150, 191));
        jLabel4.setText("Confirm Password:");

        registerbutton.setBackground(new java.awt.Color(90, 150, 191));
        registerbutton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        registerbutton.setText("Register");
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("click here to login instead");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPasswordField_confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JPasswordField_password)
                        .addComponent(JTextField_course, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(JTextField_semester, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(JTextField_userid, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259)
                .addComponent(registerbutton)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTextField_userid, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(JTextField_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextField_course, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPasswordField_confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerbutton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextField_useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_useridActionPerformed

    private void JTextField_semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_semesterActionPerformed

    private void JTextField_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_courseActionPerformed

    private void JPasswordField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPasswordField_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPasswordField_passwordActionPerformed

    private void JPasswordField_confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPasswordField_confirmpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPasswordField_confirmpasswordActionPerformed

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        //               LoginForm log=new LoginForm();
        //               log.setVisible(true);
        //           log.pack();
        //           log.setLocationRelativeTo(null);
        //          this.dispose();
        //           log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //
        String userid=JTextField_userid.getText();
        String semester=JTextField_semester.getText();
        String course=JTextField_course.getText();
        String password=String.valueOf(JPasswordField_password.getPassword());
        String confirmpassword=String.valueOf(JPasswordField_confirmpassword.getPassword());
        ///the texts are stored in the strings

        String query ="INSERT INTO mydb.`student table`(`userid`,`semester`,`course`,`password`,`confirmpassword`) VALUES(?,?,?,MD5(?),MD5(?)) ;";
        String query1="INSERT INTO mydb.`password table`(`userid`,`password`) VALUES(?,MD5(?)) ;"; //query is fine
        if(userid.equals("")){ //checking the texts ar kichui na

            JOptionPane.showMessageDialog(null,"Add a UserID");

        }else if(password.equals("")){

            JOptionPane.showMessageDialog(null,"add a password");

        }else if(!password.equals(confirmpassword)){

            JOptionPane.showMessageDialog(null,"Retype your password");

        }else if(semester.equals("")){

            JOptionPane.showMessageDialog(null,"Enter the semester you are in");

        }else if(course.equals("")){

            JOptionPane.showMessageDialog(null,"The course you are taking");

        }

        else if(!valPassword(password)){
            JOptionPane.showMessageDialog(null,"Only Alphanumeric passwords with atleast one lowercase and one uppercase are allowed");

        }

        else if(!password.equals(confirmpassword)){ //confirmation korlam ekhane

            JOptionPane.showMessageDialog(null,"Retype your password");

        }
        else if(checkUsername(userid)){
            JOptionPane.showMessageDialog(null,"This user already exists so enter your own assigned user ID");

        }
        else{
            PreparedStatement ps;
            PreparedStatement ps1;
            try{
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.setString(1,userid);
                ps.setString(2,semester);
                ps.setString(3,course);
                ps.setString(4,password);
                ps.setString(5,confirmpassword);
                /////now this is for a different table
                ps1 = MyConnection.getConnection().prepareStatement(query1);
                ps1.setString(1,userid);
                ps1.setString(2,password);

                if(ps.executeUpdate()>0&&ps1.executeUpdate()>0){
                    JOptionPane.showMessageDialog(null,"New Student Added");
                }

            }catch(SQLException ex){

                Logger.getLogger(Register.class.getName()).log(Level.SEVERE,null,ex);

            }
        }
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        LoginStudent log=new LoginStudent();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
        //    log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //
    }//GEN-LAST:event_jLabel6MouseClicked
 public boolean valPassword(String password){
    if(password.length()>7){
    if(checkPass(password)){
    return true;
    
    }else{
    return false;
    }
    }else{
    JOptionPane.showMessageDialog(null,"Too small for a password");
        return false;
    }
    
    }
    
    
    
    
    
    public boolean checkPass(String password){
    boolean hasNum = false;
    boolean hasCap = false;
    boolean hasLow=false;
    char c;
    
    for(int i =0; i < password.length();i++){
    c = password.charAt(i);
    if(Character.isDigit(c)){
    hasNum= true;
    
    }else if(Character.isUpperCase(c)){
    hasCap = true;
    
    }else if(Character.isLowerCase(c)){
    hasLow = true;
    
    }if(hasNum && hasCap && hasLow){
    return true;
    
    }   
    }
    return false;
    }
    
    
    
    
    
    
    
    
    
    public boolean checkUsername(String userid)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM mydb.`student table` WHERE `userid`=?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, userid);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checkUser = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
         return checkUser;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPasswordField_confirmpassword;
    private javax.swing.JPasswordField JPasswordField_password;
    private javax.swing.JTextField JTextField_course;
    private javax.swing.JTextField JTextField_semester;
    private javax.swing.JTextField JTextField_userid;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registerbutton;
    // End of variables declaration//GEN-END:variables
}
