 package bracuclassroom;
import javax.swing.JFrame;
import java.text.*;
import java.sql.*;
import java.util.logging.Logger;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
package bracuclassroom;

/**
 *
 * @author hamza
 */
public class ResetPassword extends javax.swing.JFrame {

 ////few garbage stuffs
    /**
     * Creates new form ResetPassword
     */
    public ResetPassword() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JPasswordField_password = new javax.swing.JPasswordField();
        JPasswordField_confirmpassword = new javax.swing.JPasswordField();
        confirmbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_userid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(75, 119, 190));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reset Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(90, 150, 191));
        jLabel2.setText("New Pass");

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(90, 150, 191));
        jLabel3.setText("Confirm Pass");

        JPasswordField_password.setBackground(new java.awt.Color(90, 150, 191));
        JPasswordField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPasswordField_passwordActionPerformed(evt);
            }
        });

        JPasswordField_confirmpassword.setBackground(new java.awt.Color(90, 150, 191));
        JPasswordField_confirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPasswordField_confirmpasswordActionPerformed(evt);
            }
        });

        confirmbutton.setBackground(new java.awt.Color(90, 150, 191));
        confirmbutton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        confirmbutton.setText("Confirm");
        confirmbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbuttonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("create a new account");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jTextField1_userid.setBackground(new java.awt.Color(90, 150, 191));
        jTextField1_userid.setForeground(new java.awt.Color(244, 244, 244));
        jTextField1_userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_useridActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(90, 150, 191));
        jLabel4.setText("User ID");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("go back to login");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(confirmbutton)
                        .addGap(105, 105, 105))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPasswordField_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_userid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPasswordField_confirmpassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1_userid, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JPasswordField_confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(confirmbutton)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPasswordField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPasswordField_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPasswordField_passwordActionPerformed

    private void JPasswordField_confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPasswordField_confirmpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPasswordField_confirmpasswordActionPerformed

    private void confirmbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbuttonActionPerformed
      //user id is in the global variable
        String userid=jTextField1_userid.getText();
        String password=String.valueOf(JPasswordField_password.getPassword());//current password
        String confirmpassword=String.valueOf(JPasswordField_confirmpassword.getPassword());
        ///the texts are stored in the strings
      
      
        if(password.equals("")){

            JOptionPane.showMessageDialog(null,"add a password");

        }else if(!password.equals(confirmpassword)){

            JOptionPane.showMessageDialog(null,"Retype your password");

        }

        else if(!valPassword(password)){
            JOptionPane.showMessageDialog(null,"Only Alphanumeric passwords are allowed ");

        }else if(checkPreviousPass(password,userid)){
        JOptionPane.showMessageDialog(null,"NO Previous Passwords ");
        
        }  
        ///////////////////////////GENJAMMM ekhan hocche
        ///////////////////////////GENJAMMM ekhan hocche
        ///////////////////////////GENJAMMM ekhan hocche
        ///////////////////////////GENJAMMM ekhan hocche
        else{ 
           
            ///insert er kaaj arki ekhane
    PreparedStatement ps;
    PreparedStatement ps1;
    ResultSet rs1;
    ResultSet rs;
           String query="INSERT INTO mydb.`password table`(`userid`,`password`) VALUES(?,MD5(?)) ;";
          String query1="UPDATE mydb.`faculty table` SET `password`=MD5(?) , `confirmpassword`=MD5(?) WHERE (`userid`=?);"; //query is fine
     
        try{
      
       
         ps = MyConnection.getConnection().prepareStatement(query);
         ps.setString(1, userid);
         ps.setString(2, password);
         //rs = ps.executeQuery(); 
         
       ps1 = MyConnection.getConnection().prepareStatement(query1);
       ps1.setString(1, password);
       ps1.setString(2, password);
       ps1.setString(3, userid);
       //rs1 = ps1.executeQuery(); 
         //i tried using the same code as the login but didnt work
         //i guess it is because im not just  checking over im executing some stuffs
      if(ps.executeUpdate()>0&&ps1.executeUpdate()>0){
        //result ashle
        JOptionPane.showMessageDialog(null,"new Pass added");
   
         }else{
         JOptionPane.showMessageDialog(null,"Incorrect UserID");
         }
      
       }catch(SQLException ex){
       
       Logger.getLogger(ResetPassword.class.getName()).log(Level.SEVERE,null,ex);
       
       }
       }
        
        ///////////////////////////GENJAMMM ekhan hocche
        ///////////////////////////GENJAMMM ekhan hocche///////////////////////////GENJAMMM ekhan hocche///////////////////////////GENJAMMM ekhan hocche
        ///////////////////////////GENJAMMM ekhan hocche
               
    }//GEN-LAST:event_confirmbuttonActionPerformed
///////////////////////////////
    ///////////////////////////////
    
   
    
    
    public boolean valPassword(String password){
    if(password.length()>7){
    if(checkPass(password)){
    return true;
    
    }else{
    return false;
    }
    }else{
    JOptionPane.showMessageDialog(null,"Too small for a password");
        return false;
    }
    
    }
    
    ///////////////////////////////
    ///////////////////////////////
    
    
   public boolean checkPass(String password){
    boolean hasNum = false;
    boolean hasCap = false;
    boolean hasLow=false;
    char c;
    
    for(int i =0; i < password.length();i++){
    c = password.charAt(i);
    if(Character.isDigit(c)){
    hasNum= true;
    
    }else if(Character.isUpperCase(c)){
    hasCap = true;
    
    }else if(Character.isLowerCase(c)){
    hasLow = true;
    
    }if(hasNum && hasCap && hasLow){
    return true;
    
    }   
    }
    return false;
    }
    
    ///////////////////////////////
    ///////////////////////////////
       public boolean checkPreviousPass(String password,String userid)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkPass = false;
        String query = "SELECT * FROM mydb.`password table` WHERE `userid`=? AND `password`=MD5(?)";
        
        try {
           ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, userid);
            ps.setString(2, password);
            rs = ps.executeQuery();
            
            if(rs.next())
           {
               checkPass = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ResetPassword.class.getName()).log(Level.SEVERE, null, ex);
       }
         return checkPass;
   }
    ////////////////////
       ////////////////////////////// JAA GENJAM EKHANEII HOCCHE
    
    
    
    
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Register rgf = new Register();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        this.dispose();
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabel6MouseClicked

       private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {                                     
        LoginForm rgf = new LoginForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        this.dispose();
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }   
    
    private void jTextField1_useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_useridActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        LoginForm rgf = new LoginForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        this.dispose();
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPasswordField_confirmpassword;
    private javax.swing.JPasswordField JPasswordField_password;
    public javax.swing.JButton confirmbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1_userid;
    // End of variables declaration//GEN-END:variables
}
